language: objective-c
osx_image: xcode10.2
sudo: false
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
xcode_workspace: SpeakTimesTable.xcworkspace
xcode_scheme: SpeakTimesTable
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
- pod install
